package com.transiva.app;
import android.Manifest;import android.content.*;import android.content.pm.PackageManager;import android.location.*;import android.net.Uri;import android.os.*;import android.widget.*;import androidx.core.content.ContextCompat;import org.json.JSONObject;import java.util.Locale;
public class MerchantLocationActivity extends MerchantBaseActivity{
 private static final int REQ=901;private TextView state;private Button save,map;private LocationManager lm;private LocationListener listener;private Location best;private final Handler h=new Handler(Looper.getMainLooper());
 @Override protected void onCreate(Bundle b){super.onCreate(b);LinearLayout root=new LinearLayout(this);setContentView(page(root));root.addView(title("Lokasi Merchant"));root.addView(sub("Kunci titik pickup sepresisi mungkin sebelum disimpan"));state=card("Belum mengambil lokasi.");root.addView(state);Button get=btn("◎ Ambil Lokasi Presisi");get.setOnClickListener(v->start());root.addView(get);map=outlineBtn("🗺 Preview Titik di Peta");map.setEnabled(false);map.setOnClickListener(v->preview());root.addView(map);save=btn("💾 Simpan Titik Merchant");save.setEnabled(false);save.setOnClickListener(v->save());root.addView(save);}
 private void start(){if(ContextCompat.checkSelfPermission(this,Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},REQ);return;}best=null;lm=(LocationManager)getSystemService(LOCATION_SERVICE);listener=l->{if(l!=null&&l.hasAccuracy()&&(best==null||l.getAccuracy()<best.getAccuracy())){best=new Location(l);showLoc();if(l.getAccuracy()<=20)stop();}};try{lm.requestLocationUpdates(LocationManager.GPS_PROVIDER,500,0,listener);}catch(Exception ignored){}try{lm.requestLocationUpdates(LocationManager.NETWORK_PROVIDER,700,0,listener);}catch(Exception ignored){}h.postDelayed(this::stop,15000);state.setText("Mencari satelit dan titik terbaik...");}
 private void showLoc(){float a=best.getAccuracy();state.setText(String.format(Locale.US,"📍 %.7f, %.7f\nAkurasi ±%.0f meter\n%s",best.getLatitude(),best.getLongitude(),a,a<=20?"Sangat baik":a<=40?"Baik":"Terlalu jauh — ambil ulang di area terbuka"));save.setEnabled(a<=40);map.setEnabled(true);}
 private void stop(){h.removeCallbacksAndMessages(null);try{if(lm!=null&&listener!=null)lm.removeUpdates(listener);}catch(Exception ignored){}if(best!=null)showLoc();}
 private void preview(){if(best==null)return;Uri u=Uri.parse("geo:"+best.getLatitude()+","+best.getLongitude()+"?q="+best.getLatitude()+","+best.getLongitude()+"(Merchant%20Transiva)");try{startActivity(new Intent(Intent.ACTION_VIEW,u));}catch(Exception e){toast("Aplikasi peta tidak tersedia");}}
 private void save(){if(best==null||best.getAccuracy()>40)return;save.setEnabled(false);MerchantNetworkExecutor.executeWrite("merchant-location",()->{try{JSONObject p=new JSONObject();p.put("latitude",best.getLatitude());p.put("longitude",best.getLongitude());p.put("accuracy_m",best.getAccuracy());JSONObject r=new JSONObject(postJson(BASE+"merchant_update_location.php",p));runOnUiThread(()->{save.setEnabled(true);toast(r.optString("message","Tersimpan"));});}catch(Exception e){runOnUiThread(()->{save.setEnabled(true);alert("Lokasi","Gagal menyimpan titik.");});}});}
 @Override protected void onDestroy(){stop();super.onDestroy();}@Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ&&ContextCompat.checkSelfPermission(this,Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED)start();}
}
