package com.transiva.app;
import android.content.*;import android.os.Build;import java.security.MessageDigest;
final class MerchantCrashReporter{
 private static final String PREF="merchant_crash_diag_v1";private MerchantCrashReporter(){}
 static void install(Context c){Thread.UncaughtExceptionHandler old=Thread.getDefaultUncaughtExceptionHandler();Thread.setDefaultUncaughtExceptionHandler((t,e)->{try{String sig=sha((e==null?"unknown":e.getClass().getName())+":"+(e==null||e.getStackTrace().length==0?"":e.getStackTrace()[0].toString()));c.getSharedPreferences(PREF,Context.MODE_PRIVATE).edit().putLong("at",System.currentTimeMillis()).putString("signature",sig).putString("type",e==null?"unknown":e.getClass().getSimpleName()).apply();}catch(Throwable ignored){}if(old!=null)old.uncaughtException(t,e);});}
 static String summary(Context c){SharedPreferences p=c.getSharedPreferences(PREF,Context.MODE_PRIVATE);long at=p.getLong("at",0);return at<=0?"Tidak ada crash lokal yang tercatat":"Crash terakhir: "+new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm",java.util.Locale.getDefault()).format(new java.util.Date(at))+" • "+p.getString("type","")+" • "+p.getString("signature","");}
 static void reportPending(MerchantBaseActivity a){try{SharedPreferences p=a.getSharedPreferences(PREF,Context.MODE_PRIVATE);String sig=p.getString("signature","");if(sig==null||sig.isEmpty()||sig.equals(p.getString("uploaded_signature","")))return;org.json.JSONObject body=new org.json.JSONObject();body.put("type",p.getString("type","client_error"));body.put("screen",a.getClass().getSimpleName());body.put("signature",sig);body.put("app_version",AppUpdateClient.installedVersionName(a));body.put("sdk",Build.VERSION.SDK_INT);MerchantNetworkExecutor.executeWrite("client-diagnostic:"+sig,()->{try{org.json.JSONObject r=new org.json.JSONObject(MerchantHttpClient.postJson(a,MerchantBaseActivity.BASE+"merchant_client_diagnostics.php",body));if(r.optBoolean("success",false))p.edit().putString("uploaded_signature",sig).apply();}catch(Exception ignored){}});}catch(Throwable ignored){}}
 private static String sha(String v)throws Exception{byte[] d=MessageDigest.getInstance("SHA-256").digest(v.getBytes("UTF-8"));StringBuilder b=new StringBuilder();for(byte x:d)b.append(String.format("%02x",x));return b.substring(0,16);}
}
