package com.transiva.app;

import android.app.AlertDialog;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.graphics.Color;
import android.view.Gravity;
import android.widget.*;
import org.json.JSONArray;
import org.json.JSONObject;

public class MerchantOrdersActivity extends MerchantBaseActivity {
    private LinearLayout root, list; private final Handler handler=new Handler(Looper.getMainLooper()); private Runnable task; private boolean firstLoad=true,updating=false; private String focusOrderId=""; private JSONArray cached=new JSONArray(); private boolean historyMode=false; private Spinner periodSpinner;
    @Override protected void onCreate(Bundle b){super.onCreate(b);focusOrderId=getIntent().getStringExtra("order_id");if(focusOrderId==null)focusOrderId="";build();}
    @Override protected void onResume(){super.onResume();start();} @Override protected void onPause(){super.onPause();stop();}
    private void build(){root=new LinearLayout(this);setContentView(page(root));root.addView(title("Pesanan Merchant"));root.addView(sub("Proses pesanan aktif, estimasi masak, dan riwayat order"));LinearLayout tabs=row();Button active=btn("Aktif");Button hist=outlineBtn("Riwayat");tabs.addView(active,new LinearLayout.LayoutParams(0,dp(48),1));tabs.addView(hist,new LinearLayout.LayoutParams(0,dp(48),1));root.addView(tabs);active.setOnClickListener(v->{historyMode=false;periodSpinner.setVisibility(Spinner.GONE);render();});hist.setOnClickListener(v->{historyMode=true;periodSpinner.setVisibility(Spinner.VISIBLE);render();});periodSpinner=new Spinner(this);periodSpinner.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Hari ini","7 hari","30 hari","Semua"}));periodSpinner.setVisibility(Spinner.GONE);periodSpinner.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,android.view.View v,int pos,long id){if(historyMode)render();}public void onNothingSelected(android.widget.AdapterView<?> p){}});root.addView(periodSpinner);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list);Button back=outlineBtn("← Kembali");back.setOnClickListener(v->finish());root.addView(back);}
    private void start(){stop();firstLoad=true;load();task=()->{if(!updating)load();handler.postDelayed(task,15000);};handler.postDelayed(task,15000);} private void stop(){if(task!=null)handler.removeCallbacks(task);} 
    private void load(){if(firstLoad){list.removeAllViews();list.addView(card("Memuat pesanan..."));}new Thread(()->{try{JSONObject r=new JSONObject(get(BASE+"getMerchantOrders.php?v="+System.currentTimeMillis()));runOnUiThread(()->{firstLoad=false;cached=r.optJSONArray("orders");if(cached==null)cached=new JSONArray();render();});}catch(Exception e){runOnUiThread(()->{firstLoad=false;list.removeAllViews();list.addView(card("Koneksi gagal saat memuat pesanan."));});}}).start();}
    private void render(){list.removeAllViews();int shown=0;for(int i=0;i<cached.length();i++){JSONObject o=cached.optJSONObject(i);if(o==null)continue;String st=o.optString("status","pending").toLowerCase();boolean fin=isFinal(st);if(historyMode!=fin)continue;if(historyMode&&!inPeriod(o))continue;if(!historyMode&&!focusOrderId.isEmpty()&&sameOrder(o,focusOrderId)){list.addView(orderView(o,true));shown++;}}
        for(int i=0;i<cached.length();i++){JSONObject o=cached.optJSONObject(i);if(o==null)continue;String st=o.optString("status","pending").toLowerCase();boolean fin=isFinal(st);if(historyMode!=fin)continue;if(historyMode&&!inPeriod(o))continue;if(!historyMode&&!focusOrderId.isEmpty()&&sameOrder(o,focusOrderId))continue;list.addView(orderView(o,false));shown++;}if(shown==0)list.addView(card(historyMode?"Belum ada riwayat pada periode ini.":"Belum ada pesanan aktif."));}
    private boolean sameOrder(JSONObject o,String id){return id.equalsIgnoreCase(s(o,"order_id","id","order_numeric_id","order_db_id"));} private boolean isFinal(String st){return st.equals("finished")||st.equals("completed")||st.equals("cancelled")||st.equals("canceled")||st.equals("merchant_rejected");}
    private boolean inPeriod(JSONObject o){int p=periodSpinner.getSelectedItemPosition();if(p==3)return true;String raw=s(o,"created_at","order_date","created");if(raw.isEmpty())return true;try{java.text.SimpleDateFormat f=new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss",java.util.Locale.US);long age=System.currentTimeMillis()-f.parse(raw).getTime();long days=p==0?1:(p==1?7:30);return age<=days*86400000L;}catch(Exception e){return true;}}
    private LinearLayout orderView(JSONObject o,boolean focused){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(14),dp(14),dp(14),dp(14));box.setBackground(focused?stroke(Color.parseColor("#F0F7FF"),BLUE,dp(18)):round(Color.WHITE,dp(18)));box.setElevation(dp(2));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(12));box.setLayoutParams(lp);String displayId=s(o,"order_id","id"),actionId=s(o,"id","order_numeric_id","order_db_id","order_id"),status=o.optString("status","pending");long price=o.optLong("price",o.optLong("total",o.optLong("grand_total",0)));String customer=s(o,"customer_name","customer","name"),phone=s(o,"customer_phone","phone"),address=s(o,"delivery_address","destination_address","address"),driver=s(o,"driver","driver_name"),note=s(o,"customer_note","note","notes","catatan");LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.HORIZONTAL);head.setGravity(Gravity.CENTER_VERTICAL);TextView ot=tv("Order #"+(displayId.isEmpty()?"-":displayId),17,NAVY,true);head.addView(ot,new LinearLayout.LayoutParams(0,-2,1));TextView badge=tv(statusLabel(status),12,BLUE,true);badge.setPadding(dp(10),dp(5),dp(10),dp(5));badge.setBackground(round(Color.parseColor("#EAF3FF"),dp(20)));head.addView(badge);box.addView(head);String cook=s(o,"cook_minutes","estimated_cook_minutes");if(!cook.isEmpty())box.addView(tv("⏱ Estimasi masak: "+cook+" menit",12,Color.parseColor("#7A4D00"),true));if(!customer.isEmpty())box.addView(tv("Customer: "+customer+(phone.isEmpty()?"":" • "+phone),13,TEXT,true));if(!address.isEmpty())box.addView(tv("Tujuan: "+address,13,MUTED,false));box.addView(tv("Driver: "+(driver.isEmpty()?"Belum ada driver":driver),13,MUTED,false));addItems(box,o);if(!note.isEmpty()){TextView nv=tv("Catatan customer: “"+note+"”",13,Color.parseColor("#7A4D00"),true);nv.setPadding(dp(12),dp(10),dp(12),dp(10));nv.setBackground(round(Color.parseColor("#FFF7E6"),dp(12)));box.addView(nv);}box.addView(tv("Total: "+rupiah(price),16,NAVY,true));if(!historyMode)addActions(box,actionId,displayId,status);return box;}
    private void addItems(LinearLayout box,JSONObject order){JSONArray items=order.optJSONArray("items");box.addView(tv("Detail Pesanan",14,NAVY,true));if(items==null||items.length()==0){box.addView(tv("Detail item belum dikirim API.",13,Color.parseColor("#B54708"),false));return;}for(int i=0;i<items.length();i++){JSONObject it=items.optJSONObject(i);if(it==null)continue;int qty=Math.max(1,it.optInt("qty",it.optInt("quantity",1)));String name=s(it,"name","menu_name","food_name","item_name");long unit=it.optLong("price",it.optLong("unit_price",0));long subtotal=it.optLong("subtotal",unit*qty);String variant=s(it,"variant","variant_name","option","options"),note=s(it,"note","notes","item_note","catatan");box.addView(tv(qty+"x "+(name.isEmpty()?"Item":name)+(subtotal>0?"  •  "+rupiah(subtotal):""),14,TEXT,true));if(!variant.isEmpty())box.addView(tv("   "+variant,12,MUTED,false));if(!note.isEmpty())box.addView(tv("   Catatan: "+note,12,Color.parseColor("#7A4D00"),false));}}
    private void addActions(LinearLayout box,String actionId,String displayId,String status){String st=status==null?"":status.trim().toLowerCase();if("pending".equals(st)){LinearLayout a=row();Button accept=btn("Terima");Button reject=outlineBtn("Tolak");a.addView(accept,new LinearLayout.LayoutParams(0,dp(48),1));a.addView(reject,new LinearLayout.LayoutParams(0,dp(48),1));box.addView(a);accept.setOnClickListener(v->showCookTime(actionId,displayId));reject.setOnClickListener(v->showRejectReasons(actionId,displayId));}else if("merchant_accepted".equals(st)){Button p=btn("Mulai Siapkan Pesanan");p.setOnClickListener(v->update(actionId,displayId,"preparing","",0));box.addView(p);}else if("preparing".equals(st)||"merchant_preparing".equals(st)){Button r=btn("✓ Pesanan Siap Diambil");r.setOnClickListener(v->update(actionId,displayId,"ready","",0));box.addView(r);}}
    private void showCookTime(String id,String displayId){final String[] labels={"10 menit","15 menit","20 menit","30 menit","45 menit"};final int[] mins={10,15,20,30,45};new AlertDialog.Builder(this).setTitle("Estimasi waktu memasak").setItems(labels,(d,w)->update(id,displayId,"merchant_accepted","",mins[w])).setNegativeButton("Batal",null).show();}
    private void showRejectReasons(String id,String displayId){final String[] reasons={"Menu habis","Restoran terlalu ramai","Restoran akan segera tutup","Pesanan tidak dapat dibuat","Lainnya"};AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Alasan Tolak Pesanan").setSingleChoiceItems(reasons,-1,null).setNegativeButton("Batal",null).setPositiveButton("Tolak Pesanan",null).create();dialog.setOnShowListener(d->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{int pos=dialog.getListView().getCheckedItemPosition();if(pos<0){toast("Pilih alasan penolakan terlebih dahulu.");return;}dialog.dismiss();if(pos==reasons.length-1)showCustomRejectReason(id,displayId);else update(id,displayId,"merchant_rejected",reasons[pos],0);}));dialog.show();}
    private void showCustomRejectReason(String id,String displayId){EditText in=input("Tuliskan alasan penolakan",android.text.InputType.TYPE_CLASS_TEXT);new AlertDialog.Builder(this).setTitle("Alasan Lainnya").setView(in).setNegativeButton("Batal",null).setPositiveButton("Tolak",(d,w)->update(id,displayId,"merchant_rejected",in.getText().toString().trim().isEmpty()?"Alasan merchant":in.getText().toString().trim(),0)).show();}
    private String statusLabel(String s){if(s==null)return"-";switch(s.trim().toLowerCase()){case"pending":return"Menunggu Merchant";case"merchant_accepted":return"Diterima Merchant";case"preparing":case"merchant_preparing":return"Sedang Disiapkan";case"ready":case"merchant_ready":return"Siap Diambil";case"merchant_rejected":return"Ditolak Merchant";case"taken":return"Driver Menuju Pickup";case"arrived_pickup":return"Driver Tiba di Resto";case"on_delivery":return"Menuju Customer";case"arrived_delivery":return"Driver Tiba di Customer";case"finished":case"completed":return"Selesai";case"canceled":case"cancelled":return"Dibatalkan";}return s;}
    private void update(String id,String displayId,String status,String rejectReason,int cookMinutes){if(id==null||id.trim().isEmpty()){alert("Data tidak lengkap","ID pesanan tidak ditemukan.");return;}updating=true;new Thread(()->{try{JSONObject p=new JSONObject();p.put("id",id);p.put("order_id",displayId);p.put("status",status);if(cookMinutes>0)p.put("cook_minutes",cookMinutes);if(!rejectReason.isEmpty())p.put("reject_reason",rejectReason);JSONObject r=new JSONObject(postJson(BASE+"updateMerchantOrder.php",p));runOnUiThread(()->{updating=false;if(r.optBoolean("success",false)){toast(r.optString("message","Berhasil"));load();}else alert("Gagal",r.optString("message","Gagal mengubah status."));});}catch(Exception e){runOnUiThread(()->{updating=false;alert("Error","Gagal mengubah status pesanan.");});}}).start();}
}
