package com.transiva.app;
import android.app.AlertDialog;import android.os.Bundle;import android.widget.*;import org.json.*;
public class MerchantDeviceSessionsActivity extends MerchantBaseActivity{
 private LinearLayout list;
 @Override protected void onCreate(Bundle b){super.onCreate(b);LinearLayout r=new LinearLayout(this);setContentView(page(r));r.addView(title("Perangkat & Sesi"));r.addView(sub("Kelola perangkat yang masih memiliki sesi Merchant aktif"));list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);r.addView(list);load();}
 private void load(){list.removeAllViews();list.addView(card("Memuat sesi..."));MerchantNetworkExecutor.executeRead(this,"merchant-sessions",()->{try{JSONObject x=new JSONObject(get(BASE+"merchant_device_sessions.php?v="+System.currentTimeMillis()));JSONArray a=x.optJSONArray("sessions");runOnUiThread(()->render(a==null?new JSONArray():a));}catch(Exception e){runOnUiThread(()->{list.removeAllViews();list.addView(card("Gagal memuat sesi perangkat."));});}});}
 private void render(JSONArray a){list.removeAllViews();if(a.length()==0){list.addView(card("Tidak ada sesi aktif."));return;}for(int i=0;i<a.length();i++){JSONObject s=a.optJSONObject(i);if(s==null)continue;int id=s.optInt("id");boolean current=s.optInt("is_current")==1;LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(14),dp(16),dp(14));c.setBackground(round(android.graphics.Color.WHITE,dp(18)));c.addView(tv((current?"📱 Perangkat ini • ":"📱 ")+s.optString("device_name","Android"),14,NAVY,true));c.addView(tv("Terakhir aktif: "+s.optString("last_used_at",s.optString("created_at","-")),11,MUTED,false));if(!current&&s.optString("revoked_at","").isEmpty()){Button b=outlineBtn("Keluarkan perangkat");b.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Keluarkan perangkat?").setMessage("Sesi pada perangkat tersebut akan langsung dicabut.").setNegativeButton("Batal",null).setPositiveButton("Keluarkan",(d,w)->revoke(id)).show());c.addView(b);}list.addView(c);}}
 private void revoke(int id){MerchantNetworkExecutor.executeWrite("revoke-session:"+id,()->{try{JSONObject p=new JSONObject();p.put("token_id",id);JSONObject r=new JSONObject(postJson(BASE+"merchant_revoke_device_session.php",p));runOnUiThread(()->{toast(r.optString("message","Sesi diperbarui"));load();});}catch(Exception e){runOnUiThread(()->toast("Gagal mengeluarkan perangkat."));}});}
}
