package com.transiva.app;
import android.app.Activity;import org.json.JSONObject;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;
/** PIN network transport isolated from PinActivity. */
final class MerchantPinRepository{
 static final class Result{final boolean success;final String code;final String message;final JSONObject data;Result(boolean s,String c,String m,JSONObject d){success=s;code=c==null?"":c;message=m==null?"":m;data=d==null?new JSONObject():d;}}
 private MerchantPinRepository(){}
 static Result request(PinActivity a,SessionManager session,String endpoint,JSONObject payload){HttpURLConnection conn=null;try{conn=(HttpURLConnection)new URL(endpoint).openConnection();conn.setRequestMethod(payload==null?"GET":"POST");conn.setConnectTimeout(25000);conn.setReadTimeout(25000);conn.setUseCaches(false);conn.setDoInput(true);conn.setRequestProperty("Accept","application/json");conn.setRequestProperty("Cache-Control","no-store");conn.setRequestProperty("Connection","close");conn.setRequestProperty("Authorization","Bearer "+safe(session.getToken()).trim());conn.setRequestProperty("X-Device-UUID",DeviceIdentityManager.getInstallationUuid(a));conn.setRequestProperty("X-Transiva-Client","Android-Native");conn.setRequestProperty("X-App-Scope","merchant");if(payload!=null){conn.setDoOutput(true);conn.setRequestProperty("Content-Type","application/json; charset=UTF-8");try(BufferedWriter w=new BufferedWriter(new OutputStreamWriter(conn.getOutputStream(),StandardCharsets.UTF_8))){w.write(payload.toString());}}int status=conn.getResponseCode();String raw=read(status>=200&&status<400?conn.getInputStream():conn.getErrorStream());JSONObject json;try{json=raw.trim().isEmpty()?new JSONObject():new JSONObject(raw.trim());}catch(Exception e){return new Result(false,"INVALID_RESPONSE","Respons server PIN tidak valid.",new JSONObject());}String code=json.optString("code","");String msg=json.optString("message",status>=200&&status<300?"Berhasil.":"Permintaan PIN gagal.");if(ForceLogoutManager.isForceLogoutCode(code))a.runOnUiThread(()->ForceLogoutManager.execute(a,code.isEmpty()?"SESSION_REVOKED":code));return new Result(status>=200&&status<300&&json.optBoolean("success",false),code,msg,json);}catch(Exception e){return new Result(false,"NETWORK_ERROR","Tidak dapat terhubung ke server. Periksa koneksi internet Anda.",new JSONObject());}finally{if(conn!=null)conn.disconnect();}}
 private static String read(InputStream s)throws Exception{if(s==null)return "";try(BufferedReader r=new BufferedReader(new InputStreamReader(s,StandardCharsets.UTF_8))){StringBuilder out=new StringBuilder();String l;while((l=r.readLine())!=null)out.append(l);return out.toString();}}
 private static String safe(String v){return v==null?"":v;}
}
